[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-F/opt/MacOSX11.3.sdk/System/Library/Frameworks",
    "-C", "link-arg=-L/opt/MacOSX11.3.sdk/usr/lib",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-F/opt/MacOSX11.3.sdk/System/Library/Frameworks",
    "-C", "link-arg=-L/opt/MacOSX11.3.sdk/usr/lib",
]
